### ISSUE TITLE
Can you make a Hackintosh with Acer nitro 5 AMD Ryzen 9 5900hx + Nividia 3070?

### ISSUE THREAD

**Issue by sawwas** [MuttakinHasib/ryzentosh-EFI#1]
Can you make a Hackintosh with Acer nitro 5 AMD Ryzen 9 5900hx + Nividia 3070?

**Comment by MuttakinHasib** [comment]
Nvidia GPU not supported

**Comment by sawwas** [comment]
Is it possible to disable nividia and enable only the amd integrated graphics card 512m?

**Comment by MuttakinHasib** [comment]
@sawwas sorry, I have no idea about this
