### ISSUE TITLE
Issue with installing Monterey on almost exact machine.

### ISSUE THREAD

**Issue by Qbaska** [MuttakinHasib/ryzentosh-EFI#2]
Hello,
First of all, I would like to thank you for sharing your EFI folder. With your files I was able to go further than with any other or with my own. Unfortunately I get boot loop after around 70% progress of installation. I can choose in OpenConopy installation. Then I get panel with all tools possible to use (or whatever this is called in Mac). What I do there is formatting my SSD, then start installation on this SSD. Everything is fine till 3/4 of the installation progress bar. Then PC restarts and starts to boot loop. I don't even have access to OpenConopy anymore, just pixelated apple logo and immediate restart (in boot loop).

**Will list my specs:**
- MoBo: same
- CPU: same
- Ram: 32GB 3200mhz (2x16)
- M.2: Some Kingstone 1TB
- SSD (for Monterey): Samsung EVO 850 250GB (connected I think to MoBo's right side SATA slot, not the bottom ones)
- GPU: 5600XT Sapphire 6G
- WIFI: some internal TP-link connected via PCI-E, i think on AX200 from intel (?) - not working!
- WIFI2: TP-link external USB antenna

**What I changed in your EFI:**
- Serial, MBL, ROM to have my own in plist (generated also for MacPro 7,1), rest untouched.
- Removed Microsoft folder from EFI (I don't know what it does, I assumed I don't need it).

**BIOS settings:**
- Everything according to **dortania** guide, except 4G (this I had to disable coz Windows does not boot).
- Bios version I think is from late 2020, the one that helps run Zen2.

**Additional info:**
- During installation process no devices are connected except USB mouse, USB with OS/EFI, wireless USB keyboard, SSD for OS, M.2 with Windows, PCI-E wifi card from TP-Link (doesn't work anyway in Mac)
- Previously I had Catalina installed, on separate SSD (**disconnected** just for safety when I try to install Monterey).
- M.2 is for Windows only (connected constantly to M.2 slot), I don't want to share it with MacOS.
- Catalina is working on 0.6.3 opencore.
- Catalina have dual boot made based on dortania guide.
- Catalina have OpenConopy as well.
- WiFi I had via TP-Link external USB antenna, especially chosen for Mac support, configured after I installed Catalina.
- Wasn't able to run TP-link connected to PCI-E, so I just bought external antenna.
- On new Monterey I would like to try install this PCI-E Wifi card, but not mandatory, I can deal with it later myself after I finish with OS installation.

I would be super grateful for any guidance on where to look to solve this issue? Unfortunately I have no logs. Your EFI doesn't show any, just graphical OpenConopy, then Monterey installer. Nothing more. No debugging, nothing.

PS. Is there a way to tip you somehow? Thanks to you I was able to save LOTS of time. I want to show my gratitude.

Best,
Qb

**Comment by MuttakinHasib** [comment]
@Qbaska solved this issue
