### ISSUE TITLE
about About cpu type  and Desktop wallpapers

### ISSUE THREAD

**Issue by shadowslei** [MuttakinHasib/ryzentosh-EFI#3]
hello，thanks U share，the EFI is perfect。
and I would like to ask how to modify the CPU model in about this mac？
and displays -> set scaled  choose other eg：1920*1080 and my desktop wallpapers is shattered like mosaic

my computer configuration is  amd 3700X 、B450M MORTAR MAX 、Sapphire RX5600XT、AOC 4k display

thanks

**Comment by MuttakinHasib** [comment]
https://github.com/acidanthera/RestrictEvents
use this kext file for CPU model

are you running on macOS 12.3 ?

**Comment by shadowslei** [comment]
yes ， I updated the 12.3，and  has the problem on 12.3？ and I need back to 12.2？

**Comment by MuttakinHasib** [comment]
last night i update from 12.2 to 12.3 and got this wallpaper issue

**Comment by shadowslei** [comment]
ok，can you resolved it？

**Comment by MuttakinHasib** [comment]
i set with my local wallpaper.

but big sur wallpaper have this issue,.i don’t know why

**Comment by shadowslei** [comment]
ok,I choose 15th of the defult desk pic tab  is not have the issue,thinks again

**Comment by shadowslei** [comment]
ok,I choose 15th of the defult desk pic tab  is not have the issue,thinks again

**Comment by shadowslei** [comment]
ok,I choose 15th of the defult desk pic tab  is not have the issue,thinks again

**Comment by shadowslei** [comment]
the wallpaper name is Catalina Silhouette,LOL

**Comment by MuttakinHasib** [comment]
@shadowslei fixed in macOS (12.3.1 )
